language: cpp
jobs:
  include:
    - os: osx
      osx_image: xcode11
      env: 
        - BUILD_TARGET=osx
    - os: linux
      env: 
        - BUILD_TARGET=linux
    - os: freebsd
      compiler: clang
      env:
        - BUILD_TARGET=freebsd
    - os: osx
      osx_image: xcode11
      env: 
        - BUILD_TARGET=ios
    - os: linux
      env:
        - BUILD_TARGET=android
        - NDK_VER=r16b

install:
  - travis/install.sh

script:
  - travis/build.sh
